SCOREBOARD:
    TICKS: 20
    TITLE: "&b&leAuth Core"
    LINES:
        - "&7&m---------------------------"
        - ""
        - "&b&lLogin"
        - "&7/login <pass>"
        - ""
        - "&b&lRegister"
        - "&7/register <pass> <pass>"
        - ""
        - "&bplay.server.net"
        - "&7&m---------------------------"

MESSAGES:
    ONLY_PLAYERS: "&cThis command can only be used by players."
    NO_PERMISSIONS: "&cYou do not have permission to use this command."
    SPAWN_SET: "&aSpawn point has been successfully set."

OPTIONS:
    HIDE_PLAYERS: true
    CANCEL_MOVEMENT: true
    CANCEL_CHAT: true